remote_theme: wet-boew/gcweb-jekyll
title: Search UI for Canada.ca Search

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default
